### products index
GET  http://localhost:3000/products.json

### product create
POST  http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test name",
  "description": "test description",
  "price": 32,
}

### products show
GET http://localhost:3000/products/7.json

### Product Update
PATCH http://localhost:3000/products/7.json
Content-Type: application/json

{ "price": 100 }

### Product Destroy
DELETE http://localhost:3000/products/9.json

### User Create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Bill",
  "email": "bill@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "bill@example.com",
  "password": "password"
}

### ordercreate
POST http://localhost:3000/orders.json
Authorization: Bearer "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc4NTEzOTF9.iyEiHkC_k3UQ4PueYYhy41oNtC5BhkqgH9ITHjxQOK4"
Content-Type: application/json



### order show
GET http://localhost:3000/orders/1.json
Authorization: Bearer "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc4NTEzOTF9.iyEiHkC_k3UQ4PueYYhy41oNtC5BhkqgH9ITHjxQOK4"

### orders index
GET http://localhost:3000/orders.json
Authorization: Bearer "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc4NTEzOTF9.iyEiHkC_k3UQ4PueYYhy41oNtC5BhkqgH9ITHjxQOK4"

### Carted products create
POST http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NTgyNTQ0MzN9.6uZOqun8kUtCvv3pZ_JJoNqY5Iv56AHCfrvYZhoRbqI
Content-Type: application/json

{
  "product_id": 7,
  "quantity": 3,
  "status": "carted",
  "order_id": "nil"
}


