
GET  http://localhost:3000/products/.json
###


###
PATCH http://localhost:3000/products(idhere).json
Content-Type: application/json

{"title": "typewriter"}

###
DELETE http://localhost:3000/products(idhere).json
###
POST  http://localhost:3000/products.json

{
  "name": "test name",
  "description": "test description",
  "image_url": "test image_url",
  "price": "price"

}
#Content-Type: application/json

